# Generated by Django 5.1.2 on 2024-10-17 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_requisicoesrecebidas_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicoesrecebidas',
            name='body',
            field=models.TextField(blank=True, null=True, verbose_name='Body'),
        ),
    ]
