# Generated by Django 5.1.2 on 2024-10-17 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_requisicoesrecebidas_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisicoesrecebidas',
            name='body',
        ),
        migrations.AddField(
            model_name='requisicoesrecebidas',
            name='retorno',
            field=models.TextField(blank=True, null=True, verbose_name='retorno'),
        ),
    ]
