# Generated by Django 5.1.2 on 2024-10-17 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_requisicoesrecebidas_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicoesrecebidas',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Criação'),
        ),
    ]
